gini/gini-mobile-android

- core-api-library/library/src/androidTest/java/net/gini/android/core/api/internal/GiniCoreAPIIntegrationTest.java
> chore(core-api-library): Reenable disabled test

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt
- health-sdk/sdk/src/main/res/drawable/ghs_payment_details_info_bar_background.xml
- health-sdk/sdk/src/main/res/layout/ghs_fragment_review.xml
- health-sdk/sdk/src/main/res/values/colors.xml
- health-sdk/sdk/src/main/res/values/strings.xml
- health-sdk/sdk/src/main/res/values/styles.xml
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewViewModelTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/test/TestCoroutineRule.kt
The info bar is shown on launch and slides out after a delay.
> feat(health-sdk): Show info bar on review screen

- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/review/ReviewActivity.kt
- health-sdk/sdk/src/doc/source/flow.rst
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewFragmentTest.kt
Makes it consistent with the iOS version.
> refactor(health-sdk): Rename `onPayClicked()` to `onNextClicked()`

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/pager/DocumentPageAdapter.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/util/Extensions.kt
> Close button hides keyboard if open

- README.md
Transferred and extended the information from our monorepo ADR:
https://wiki.i.gini.net/display/ADR/ADR+05+-+Monorepo+for+mobile+projects
> chore: Document how the monorepo works and how to use it in the readme

- RELEASE-ORDER.md
- bank-api-library/library/gradle.properties
- bank-api-library/library/src/doc/source/guides/getting-started.rst
- bank-sdk/sdk/gradle.properties
- bank-sdk/sdk/src/doc/source/getting-started.rst
- capture-sdk/default-network/gradle.properties
- capture-sdk/default-network/src/main/java/net/gini/android/capture/network/GiniCaptureDefaultNetworkService.java
- capture-sdk/sdk/gradle.properties
- capture-sdk/sdk/src/doc/source/getting-started.rst
- capture-sdk/sdk/src/doc/source/integration.rst
- core-api-library/library/gradle.properties
- core-api-library/library/src/androidTest/java/net/gini/android/core/api/RequestQueueBuilderTest.java
- core-api-library/library/src/androidTest/java/net/gini/android/core/api/internal/GiniCoreAPIBuilderTest.java
- core-api-library/library/src/androidTest/java/net/gini/android/core/api/internal/GiniCoreAPIIntegrationTest.java
- core-api-library/library/src/main/java/net/gini/android/core/api/RequestQueueBuilder.java
- core-api-library/library/src/main/java/net/gini/android/core/api/internal/GiniCoreAPIBuilder.java
Includes changes for three sub-tickets: 
* https://ginis.atlassian.net/browse/PIA-2181
* https://ginis.atlassian.net/browse/PIA-2187
* https://ginis.atlassian.net/browse/PIA-2188
> Pia 1960 custom trust manager

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/BankSelectionFragment.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/util/Extensions.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewViewModelTest.kt
* Fixes input field error message logic according to the rules here: https://ginis.atlassian.net/browse/PIA-2337
* Fixes crash when two or more banking apps are selected at the same time.
> Pia 2337 fix input field error message logic

- capture-sdk/sdk/src/doc/source/customization-guide.rst
> docs(capture-sdk): Add info on how style the "Back to camera" button

- .git-stuff/commit-msg-template.txt
As our team grows I think it's helpful to clarify when to use which commit type.
Any improvement feedback is very welcome. 😃 
Once we agree on the final version, I'd update it in the iOS monorepo as well.
> chore: Clarify conventional commit type descriptions

- bank-sdk/sdk/src/main/res/layout/gbs_fragment_line_item_details.xml
> feat(bank-sdk): Remove multiplication symbol from line item details screen

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/details/LineItemDetailsFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/details/LineItemDetailsScreenContract.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/details/LineItemDetailsScreenPresenter.kt
- bank-sdk/sdk/src/main/res/layout/gbs_fragment_line_item_details.xml
- bank-sdk/sdk/src/main/res/layout/gbs_item_digital_invoice_footer.xml
- bank-sdk/sdk/src/main/res/layout/gbs_item_digital_invoice_line_item.xml
- bank-sdk/sdk/src/main/res/values/dimens.xml
- bank-sdk/sdk/src/test/java/net/gini/android/bank/sdk/capture/digitalinvoice/details/LineItemDetailsScreenPresenterTest.kt
> feat(bank-sdk): Line item quantity input is limited to be between 1 and 99,999

- bank-sdk/sdk/src/main/res/values/strings.xml
> fix(bank-sdk): Fixes two typos in the German texts

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/details/LineItemDetailsFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/details/LineItemDetailsScreenContract.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/details/LineItemDetailsScreenPresenter.kt
> fix(bank-sdk): Save line item changes only when pressing save

- bank-sdk/screen-api-example-app/src/main/res/values/themes.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_onboarding_page.xml
- capture-sdk/sdk/src/main/res/values/styles.xml
To test it uncomment the lines I added to the `themes.xml`.
> Pia 2806 onboarding text align

- .github/workflows/bank-sdk.check.yml
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/Configuration.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/DefaultPages.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingFragment.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingFragmentInterface.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingFragmentListener.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/view/OnboardingIllustrationAdapter.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/view/OnboardingNavigationBarBottomAdapter.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/view/InjectedViewAdapter.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/view/InjectedViewContainer.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/view/NavigationBarTopAdapter.kt
Adds reference documentation and removes three classes from the public API.
> Pia 2750 update reference documentation

- bank-sdk/component-api-example-app/src/main/AndroidManifest.xml
- bank-sdk/screen-api-example-app/src/main/AndroidManifest.xml
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/LineItemsAdapter.kt
- capture-sdk/component-api-example-app/src/main/AndroidManifest.xml
- capture-sdk/screen-api-example-app/src/main/AndroidManifest.xml
- capture-sdk/sdk/src/doc/source/features.rst
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/FileChooserActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/util/AndroidHelper.java
The changes are in preparation for targeting Android 13 early next year. For now we keep targeting Android 12.
Test on Android 12 and 13 while targeting Android 12 and also while targeting Android 13.
> Pia 3021 target android 13 fixes

- bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/MainActivity.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/CaptureFlowContract.kt
Testing instructions: https://ginis.atlassian.net/browse/PIA-3094?focusedCommentId=19164
> Pia 3094 fix file import error forwarding

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
Testing instructions: https://ginis.atlassian.net/browse/PIA-3095?focusedCommentId=19165
> fix(bank-sdk): Launch single page review screen for "open with" if multi-page is disabled

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/view/NavigationBarTopAdapter.kt
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/values/styles.xml
> feat(capture-sdk): Injected toolbar customisation

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
> fix(capture-sdk): Camera focus indicator fix

- capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/MainActivity.java
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml
> fix(capture-sdk): Items positioning on camera screen

- capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/MainActivity.java
- capture-sdk/sdk/src/test/java/net/gini/android/capture/review/multipage/MultipageReviewFragmentTest.kt
> fix(capture-sdk): Launch the tests

- capture-sdk/screen-api-example-app/src/main/res/values/styles.xml
- capture-sdk/sdk/src/main/res/values-night/styles.xml
- capture-sdk/sdk/src/main/res/values/styles.xml
Status bar default color change
https://ginis.atlassian.net/browse/PIA-3178
Please review the Pull Request checklist from our [contribution guidelines](https://github.com/gini/.github/blob/master/.github/CONTRIBUTING.md)
> feat(capture-sdk): Changed status bar color

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/camera/view/QRCodePopup.kt
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/values-en/strings.xml
- capture-sdk/sdk/src/main/res/values/dimens.xml
- capture-sdk/sdk/src/main/res/values/strings.xml
PIA-3279
Unknown QR code UI updated and logic of showing. 
To remove the flashing, between each show there is a one-second delay.
> fix(capture-sdk): Unknown qr code updated

- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCaptureFileImport.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/document/ImageDocument.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/document/ImageMultiPageDocument.java
Skip review on external files
https://ginis.atlassian.net/browse/PIA-3293
Please review the Pull Request checklist from our [contribution guidelines](https://github.com/gini/.github/blob/master/.github/CONTRIBUTING.md)
> feat(capture:sdk): Skip review on "open with" files

- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewActivity.java
- capture-sdk/sdk/src/main/res/layout/gc_activity_multi_page_review.xml
PIA-2965
Top bar injected into Review Screen.
> fix(capture-sdk): Review screen top bar injected

- capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/MainActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/view/OnButtonLoadingIndicatorAdapter.kt
- capture-sdk/sdk/src/main/res/layout/gc_fragment_multi_page_review.xml
- capture-sdk/sdk/src/main/res/values/dimens.xml
- capture-sdk/sdk/src/main/res/values/styles.xml
PIA 3185
Custom loading indicator for the Review screen.
> fix(capture-sdk): Button custom indicator

- capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_multi_page_review.xml
- capture-sdk/sdk/src/main/res/layout/gc_photo_thumbnail.xml
- capture-sdk/sdk/src/main/res/values/styles.xml
- capture-sdk/sdk/src/main/res/values/typography.xml
- margin fixed
- changed style name and TextView style added
PIA-2967
> fix(capture-sdk): changed style name

- capture-sdk/sdk/src/main/res/layout/gc_fragment_multi_page_review.xml
PIA-3363
- fixed top margins in review screen
> fix(capture-sdk): margin fix

- capture-sdk/sdk/src/main/java/net/gini/android/capture/help/HelpItemsAdapter.kt
- capture-sdk/sdk/src/main/res/values-en/strings.xml
- capture-sdk/sdk/src/main/res/values/strings.xml
- Fixed German and English localization
- Changed orders of help items to match design and iOS
> fix(capture-sdk): PIA-3362

- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_onboarding.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_onboarding_page.xml
PIA-3159
- Fix for pages indicator being misplaced in landscape
> fix(capture-sdk): land indicator fix

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/res/values-en/strings.xml
- capture-sdk/sdk/src/main/res/values/strings.xml
- the bottom bar was removed in only QR code mode
- added missing string scan
PIA-3373
> feat(capture-sdk): 

- core-api-library/library/src/main/java/net/gini/android/core/api/internal/GiniCoreAPIBuilder.kt
> feat(core-api-library): Increase default timeout to 60 seconds

- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_item_multi_page_preview.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_item_multi_page_preview.xml
- capture-sdk/sdk/src/main/res/layout/gc_item_multi_page_preview.xml
- capture-sdk/sdk/src/main/res/values-night/styles.xml
- capture-sdk/sdk/src/main/res/values/attrs.xml
- capture-sdk/sdk/src/main/res/values/styles.xml
> feat(capture-sdk):

- capture-sdk/sdk/src/main/res/layout/gc_fragment_multi_page_review.xml
- indicator margin set to 8dp
PIA-3398
> fix(capture-sdk):

- capture-sdk/component-api-example-app/src/main/java/net/gini/android/capture/component/camera/CameraScreenHandler.java
- capture-sdk/example-app-shared-code/src/main/java/net/gini/android/capture/example/shared/RuntimePermissionHandler.java
- capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/MainActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/ui/AlertDialogFragment.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml
> Pia 3412 fixed dialog crash

- bank-sdk/sdk/src/main/res/layout-sw600dp-land/gbs_fragment_digital_invoice_onboarding.xml
- bank-sdk/sdk/src/main/res/layout-sw600dp/gbs_fragment_digital_invoice_onboarding.xml
- bank-sdk/sdk/src/main/res/layout/gbs_fragment_digital_invoice_onboarding.xml
- Fixed fragment context in onboarding layouts
PIA-3559
> feat(bank-sdk):

- capture-sdk/sdk/src/doc/source/customization-guide.rst
> docs(capture-sdk): Add figma link for analysis screen customisation

- capture-sdk/sdk/src/doc/source/customization-guide.rst
> docs(capture-sdk): Add figma link for no results screen customisation

- bank-sdk/sdk/src/main/res/layout/gbs_fragment_digital_invoice_onboarding.xml
- onboarding scrollable 
Pia 3576
> fix(bank-sdk):

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/help/HelpActivity.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorActivity.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/help/FileImportActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/help/HelpActivity.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/help/PhotoTipsActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/help/SupportedFormatsActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/noresults/NoResultsFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/view/NavigationBarTopAdapter.kt
> feat(capture:sdk):

- bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/ExtractionsActivity.kt
- bank-sdk/screen-api-example-app/src/main/res/drawable/edittext_selector.xml
- bank-sdk/screen-api-example-app/src/main/res/layout/item_extraction.xml
- capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/ExtractionsActivity.kt
- capture-sdk/screen-api-example-app/src/main/res/drawable/edittext_selector.xml
- capture-sdk/screen-api-example-app/src/main/res/layout/item_extraction.xml
This contains bank sdk changes as well
> Pia 3728 capture extractions edit

- bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/MainActivity.kt
- bank-sdk/screen-api-example-app/src/main/res/layout/activity_main.xml
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceBottomSheet.kt
> feat(bank-sdk): Remove multiple currencies config option

- bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/ExtractionsActivity.kt
- bank-sdk/screen-api-example-app/src/main/res/drawable/edittext_selector.xml
- bank-sdk/screen-api-example-app/src/main/res/layout/item_extraction.xml
- bank-sdk/screen-api-example-app/src/main/res/menu/menu_extractions.xml
- gradle/libs.versions.toml
Please check values sent in network inspector, at me now the data sent looks fine
> Pia 3892 old bank extractions edit

- bank-sdk/sdk/src/main/res/layout/gbs_edit_item_bottom_sheet.xml
> fix(bank-sdk): Add missing content description for edit item sheet close button

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/LineItemsAdapter.kt
- bank-sdk/sdk/src/main/res/layout/gbs_item_digital_invoice_addon.xml
Also contains fix for PIA-3933
> Pia 3917 bank detail accessibility

- bank-sdk/sdk/src/main/res/layout/gbs_edit_item_bottom_sheet.xml
- bank-sdk/sdk/src/main/res/values-en/strings.xml
- bank-sdk/sdk/src/main/res/values/strings.xml
> feat(bank-sdk): Add content description for "-" and "+" buttons on line item edit sheet

- capture-sdk/sdk/src/main/res/menu/gc_camera.xml
- capture-sdk/sdk/src/main/res/menu/gc_navigation_bar_top_close.xml
- capture-sdk/sdk/src/main/res/values-en/strings.xml
- capture-sdk/sdk/src/main/res/values/strings.xml
@llevente I recreated PR #289  because after deleting the `new-ui` branch it automatically closed it. I'm sorry I was not aware of that.
[NOTE]: PIA-3930 also in this PR
[NOTE]: Problem occured when bottom bar was activated so we used in the topbar the menu items... it seems like for menu items the title overrides the contentDescription so i changed the title. This could be an issue if more menus will be added and there will be no space for icons so the dropdown list shows with the titles.... Please consider if this can be a real issue.
> Pia 3926 help accessibility talkbar

- RELEASE-ORDER.md
- bank-api-library/library/gradle.properties
- bank-api-library/library/src/doc/source/guides/getting-started.rst
- bank-sdk/sdk/gradle.properties
- bank-sdk/sdk/src/doc/source/getting-started.rst
- capture-sdk/default-network/gradle.properties
- capture-sdk/sdk/gradle.properties
- capture-sdk/sdk/src/doc/source/getting-started.rst
- capture-sdk/sdk/src/doc/source/integration.rst
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/storage/ImageDiskStore.java
- capture-sdk/sdk/src/test/java/net/gini/android/capture/internal/storage/ImageDiskStoreTest.java
- core-api-library/library/gradle.properties
- health-api-library/library/gradle.properties
- health-api-library/library/src/doc/source/guides/getting-started.rst
- health-sdk/sdk/gradle.properties
- health-sdk/sdk/src/doc/source/setup.rst
Release candidates for 1.x.x versions of:
* Bank SDK
* Capture SDK
* Health SDK
* all api libraries
> Pia 4066 pia 4081 release candidates for 1.x.x versions

- bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/ExtractionsActivity.kt
- bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/MainActivity.kt
- bank-sdk/sdk/src/androidTest/java/net/gini/android/bank/sdk/ExtractionFeedbackIntegrationTest.kt
- bank-sdk/sdk/src/doc/source/capture-features.rst
- bank-sdk/sdk/src/doc/source/customization-guide.rst
- bank-sdk/sdk/src/doc/source/integration.rst
- bank-sdk/sdk/src/doc/source/migrate-to-3-0-0.rst
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
- capture-sdk/default-network/src/androidTest/java/net/gini/android/capture/network/ExtractionFeedbackIntegrationTest.kt
- capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/ExtractionsActivity.kt
- capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/MainActivity.java
- capture-sdk/sdk/src/androidTest/java/net/gini/android/capture/analysis/AnalysisScreenTest.java
- capture-sdk/sdk/src/doc/source/customization-guide.rst
- capture-sdk/sdk/src/doc/source/features.rst
- capture-sdk/sdk/src/doc/source/integration.rst
- capture-sdk/sdk/src/doc/source/migrate-to-3-0-0.rst
- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragmentListener.java
- capture-sdk/sdk/src/test/java/net/gini/android/capture/analysis/AnalysisActivityTest.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/analysis/AnalysisFragmentImplTest.java
- capture-sdk/sdk/src/test/java/net/gini/android/capture/analysis/AnalysisScreenPresenterTest.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/camera/CameraActivityTest.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/camera/CameraFragmentImplTest.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/help/HelpActivityTest.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/review/multipage/MultipageReviewActivityTest.kt
Aligns cleanup logic with iOS: no cleanup is required before restarting the SDK.
> Pia 4178 allow reinitialization without cleanup

- capture-sdk/sdk/src/main/res/layout/gc_activity_file_chooser.xml
- capture-sdk/sdk/src/main/res/values/colors.xml
> fix(capture-sdk): Add background color resource for file provider

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/camera/view/QRCodePopup.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/qrcode/PaymentQRCodeReader.java
> fix(capture-sdk): Fix QR code stuck

- bank-sdk/example-app/src/main/res/values/strings.xml
- capture-sdk/sdk/src/main/res/values-en/strings.xml
- capture-sdk/sdk/src/main/res/values/strings.xml
> fix: Fix spelling errors in SDK

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationViewModel.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisScreenPresenter.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraActivity.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorFragmentImpl.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/noresults/NoResultsFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/AnalysisScreenEvent.java
> feat(capture-sdk): Add event trackers for NO_RESULT, RETRY, and ERROR

- core-api-library/library/src/main/java/net/gini/android/core/api/DocumentRemoteSource.kt
- health-api-library/library/src/main/java/net/gini/android/health/api/HealthApiDocumentRepository.kt
> fix(health-api-library): Use base url configuration for page image requests

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/core/di/GiniExampleModule.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/pay/PayActivity.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/pay/PayViewModel.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/review/ReviewActivity.kt
> fix(bank-sdk): Fix example app crashing when opened by health SDK

- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/iban/IBANKnowledge.kt
> feat(capture-sdk): Configure regex to handle short multiline IBANs

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationActivity.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationViewModel.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/data/Configuration.kt
- bank-sdk/example-app/src/main/res/layout/activity_configuration.xml
- bank-sdk/example-app/src/main/res/values/strings.xml
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/Configuration.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
> feat(capture-sdk): Disable flash by default

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
> fix(capture-sdk): Remove qr-code deletion from camera screen

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationActivity.kt
- bank-sdk/example-app/src/main/res/drawable/ic_close.xml
- fix app crash when switching to dark mode in configuration screen
- fix close button color in dark mode
> fix(bank-sdk): Fix example app bugs

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml
Fixes the following bugs:
1. IBAN detection not working if QR code scanning is disabled: https://ginis.atlassian.net/browse/PP-312
2. Wrong focus indicator position: https://ginis.atlassian.net/browse/PP-313
> Pp 312 pp 313 fix iban detector not enabled and fix focus indicator position

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/bankselection/BankSelectionBottomSheet.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/paymentcomponent/PaymentComponentView.kt
- health-sdk/sdk/src/main/res/drawable/ghs_bordered_background.xml
- health-sdk/sdk/src/main/res/drawable/ghs_selectable_payment_provider_background.xml
- health-sdk/sdk/src/main/res/layout/ghs_bottom_sheet_bank_selection.xml
- health-sdk/sdk/src/main/res/layout/ghs_item_payment_provider_app.xml
- health-sdk/sdk/src/main/res/layout/ghs_payment_provider_selector_button.xml
- health-sdk/sdk/src/main/res/layout/ghs_view_payment_component.xml
- health-sdk/sdk/src/main/res/values-night/colors.xml
- health-sdk/sdk/src/main/res/values/colors.xml
- health-sdk/sdk/src/main/res/values/styles.xml
Added rounded corners to payment provider app icons in `PaymentComponentView` & `BankSelectionBottomSheet` items.
> IPC-171 & IPC-170 rounded corners payment provider icon

- capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorType.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/error/ErrorTypeTest.kt
> fix(capture-sdk): Fix crash on 400 upload error

- bank-sdk/sdk/src/main/res/values-en/strings.xml
- bank-sdk/sdk/src/main/res/values/strings.xml
> fix(bank-sdk): Edit third help item text in RA

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/GiniHealth.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/paymentcomponent/PaymentComponent.kt
- health-sdk/sdk/src/main/res/color-night/ghs_bottom_sheet_scrim.xml
- health-sdk/sdk/src/main/res/color/ghs_bottom_sheet_scrim.xml
- health-sdk/sdk/src/main/res/values-night/colors.xml
- health-sdk/sdk/src/main/res/values/colors.xml
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/GiniHealthTest.kt
Please view the commits for details.
> Small health sdk fixes

- RELEASE-ORDER.md
- bank-sdk/sdk/gradle.properties
- bank-sdk/sdk/src/doc/source/getting-started.rst
> feat(bank-sdk): Bump version to 3.11.0

- health-sdk/sdk/src/main/res/layout/ghs_view_payment_component.xml
- health-sdk/sdk/src/main/res/values/typography.xml
- Switched to using `lineSpacingMultiplier` rather than `lineHeight`
- Added content description for `MoreInformation` button
> Ipc 176 accessibility payment component

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/paymentcomponent/PaymentComponent.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/paymentComponent/PaymentComponentTest.kt
> fix(health-sdk): Restore saved selected payment provider even if it is not installed

- health-api-library/library/src/androidTest/java/net/gini/android/health/api/GiniHealthAPIBuilderTest.kt
- health-api-library/library/src/main/java/net/gini/android/health/api/GiniHealthAPIBuilder.kt
- health-api-library/library/src/main/java/net/gini/android/health/api/HealthApiDocumentRepository.kt
- health-api-library/library/src/main/java/net/gini/android/health/api/models/PaymentProvider.kt
- health-api-library/library/src/main/java/net/gini/android/health/api/response/PaymentProviderResponse.kt
- health-api-library/library/src/test/java/net/gini/android/health/api/HealthApiDocumentRemoteSourceTest.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/paymentcomponent/PaymentComponent.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/bankselectionbottomsheet/BankSelectionBottomSheetTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/bankselectionbottomsheet/BankSelectionViewModelTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/moreinformation/MoreInformationTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/moreinformation/MoreInformationViewModelTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/paymentComponent/PaymentComponentTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/paymentprovider/PaymentProviderAppTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewViewModelTest.kt
- Added support for gpcSupportedPlatforms and `openWithSupportedPlatforms`
- Add filtering in `HealthApiDocumentRepository`
> Ipc 260 open with and gpc supported

- capture-sdk/sdk/src/main/java/com/ortiz/touch/TouchImageView.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorFragmentImpl.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/help/HelpFragment.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/FileChooserFragment.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/noresults/NoResultsFragmentImpl.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/previews/PreviewPagesAdapter.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/zoom/ZoomInPreviewFragment.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsEvent.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsEventTracker.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsExtraProperties.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsMappers.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/analysis/AnalysisFragmentTest.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/analysis/AnalysisScreenPresenterTest.kt
> feat(capture-sdk): User jorney analytics. Help screen

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/analytics/DigitalInvoiceAnalyticsExt.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceBottomSheet.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceScreenPresenter.kt
- capture-sdk/sdk/build.gradle.kts
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsEvent.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsExtraProperties.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsScreen.kt
- capture-sdk/sdk/src/test/java/net/gini/android/capture/onboarding/OnboardingScreenPresenterTest.kt
> feat(bank-sdk): Add return assistant user analytics events 

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
> fix(capture-sdk): Fix sending unknown qr code in user journey

- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesActivity.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesViewModel.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/paymentcomponent/PaymentComponent.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/paymentComponent/PaymentComponentTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewFragmentTest.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewViewModelTest.kt
Loading the payment information is handled in the ReviewFragment by showing a loading indicator until the payment information has been loaded.
IPC-271
> feat(health-sdk): Create the ReviewFragment synchronously

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/test/java/net/gini/android/capture/camera/CameraFragmentImplTest.kt
> feat(capture-sdk): Fix camera screen analytics events

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/onboarding/DigitalInvoiceOnboardingFragment.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsEvent.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/tracking/useranalytics/UserAnalyticsScreen.kt
> feat(capture-sdk): Add RA onboarding analytics events

- capture-sdk/sdk/src/main/java/net/gini/android/capture/noresults/NoResultsFragmentImpl.java
> feat(capture-sdk): Fix navigation issue from No Results screen

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/MainActivity.kt
> fix(bank-sdk): Fix Camera Permission flow for Example App

- health-sdk/example-app/src/main/AndroidManifest.xml
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/MainActivity.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/AppCompatThemeInvoicesActivity.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesActivity.kt
- health-sdk/example-app/src/main/res/layout/activity_main.xml
- health-sdk/sdk/src/main/res/layout/ghs_bottom_sheet_install_app.xml
- health-sdk/sdk/src/main/res/layout/ghs_bottom_sheet_open_with.xml
- health-sdk/sdk/src/main/res/layout/ghs_fragment_review.xml
- health-sdk/sdk/src/main/res/layout/ghs_item_page_error.xml
- health-sdk/sdk/src/main/res/layout/ghs_payment_provider_picker_button.xml
- health-sdk/sdk/src/main/res/layout/ghs_view_payment_component.xml
Please see the commit messages for details.
> Ipc 282 fix for appcompat theme

- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/util/recyclerview/SnappedItemChangeRecyclerViewListener.kt
> fix(capture-sdk): Fix page_swiped Analytics event

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationActivity.kt
- bank-sdk/example-app/src/main/res/drawable/bg_round_corners.xml
- bank-sdk/example-app/src/main/res/layout/activity_configuration.xml
- bank-sdk/example-app/src/main/res/layout/layout_analysis_toggles.xml
- bank-sdk/example-app/src/main/res/layout/layout_bottom_navigation_toggles.xml
- bank-sdk/example-app/src/main/res/layout/layout_camera_toggles.xml
- bank-sdk/example-app/src/main/res/layout/layout_debug_development_toggles.xml
- bank-sdk/example-app/src/main/res/layout/layout_feature_toggles.xml
- bank-sdk/example-app/src/main/res/layout/layout_help_toggles.xml
- bank-sdk/example-app/src/main/res/layout/layout_onboarding_toggles.xml
- bank-sdk/example-app/src/main/res/layout/layout_return_assistant_toggles.xml
- bank-sdk/example-app/src/main/res/layout/layout_ui_customization_toggles.xml
- bank-sdk/example-app/src/main/res/values/strings.xml
PP-516
There is no switch added to enable/disable the user tracking in the SDK. Only configuration screen is redesigned!
> feat(bank-sdk): Redesign configuration screen in example app

- merchant-sdk/example-app/src/main/java/net/gini/android/merchant/sdk/exampleapp/configuration/ConfigurationFragment.kt
- merchant-sdk/example-app/src/main/res/layout/fragment_invoice_details.xml
- merchant-sdk/sdk/src/main/java/net/gini/android/merchant/sdk/review/ReviewFragment.kt
Please refer to commit messages for details.
> Fix(merchant sdk) fixes for EC 60

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/MainActivity.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/FileChooserFragment.kt
Reverts gini/gini-mobile-android#484
> Revert "Pp 197 migrate from start activity for result to register for result"

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
> fix(capture-sdk): Hide activityIndicator after recognition fails

- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_error.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_error.xml
- capture-sdk/sdk/src/main/res/values-sw600dp-land/dimens.xml
- capture-sdk/sdk/src/main/res/values-sw600dp/dimens.xml
- capture-sdk/sdk/src/main/res/values/dimens.xml
> fix(capture-sdk): Remove white spaces on error screen

- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/camera/photo/ImmutablePhoto.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
> fix(capture-sdk): Fix loading indicator hiding

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/LineItemsAdapter.kt
> fix(bank-sdk): Fix crash. Add IntervalClickListener

- bank-sdk/sdk/build.gradle.kts
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenModule.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/di/IsolatedKoinContext.kt
- gradle/libs.versions.toml
refactor(bank-sdk): Skonto feature. Implement koin
PP-673
> refactor(bank-sdk): Skonto feature. Implement koin

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationActivity.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationViewModel.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/data/Configuration.kt
- bank-sdk/example-app/src/main/res/layout/layout_feature_toggles.xml
- bank-sdk/example-app/src/main/res/values/strings.xml
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/CaptureFlowFragment.kt
> feat(bank-sdk): Add switch to disable skonto in configuration screen

- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
> fix(capture-sdk) Add contentDescription for tablet layouts

- .github/workflows/capture-sdk.check.yml
Should be merged after the scheduled releases have been published.
> ci(capture-sdk): Run instrumented tests in the check workflow

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/paymentcomponent/PaymentComponentView.kt
- health-sdk/sdk/src/main/res/layout/ghs_view_payment_component.xml
> ipc 317 - fix(health-sdk): Fixed payment component view UI

- health-sdk/sdk/src/doc/source/customization.rst
- health-sdk/sdk/src/main/res/layout/ghs_view_payment_component.xml
- health-sdk/sdk/src/main/res/values/styles.xml
> fix(health-sdk): Fixed payment component styling

- bank-api-library/library/src/test/java/net/gini/android/bank/api/BankApiDocumentRemoteSourceTest.kt
- core-api-library/library/src/androidTest/java/net/gini/android/core/api/authorization/AnonymousSessionManagerTest.kt
- core-api-library/library/src/main/java/net/gini/android/core/api/authorization/AnonymousSessionManager.kt
- core-api-library/library/src/main/java/net/gini/android/core/api/authorization/UserRemoteSource.kt
- core-api-library/library/src/main/java/net/gini/android/core/api/authorization/UserRepository.kt
- core-api-library/library/src/main/java/net/gini/android/core/api/authorization/UserService.kt
- core-api-library/library/src/test/java/net/gini/android/core/api/DocumentRemoteSourceTest.kt
- core-api-library/library/src/test/java/net/gini/android/core/api/authorization/UserRemoteSourceTest.kt
- core-api-library/shared-tests/src/main/java/net/gini/android/core/api/test/shared/GiniCoreAPIIntegrationTest.kt
> feature(core-api-library) Remove oauth/check_token request

- .github/workflows/bank-sdk.publish.example.yml
- .github/workflows/health-sdk.publish.example.yml
- .github/workflows/merchant-sdk.publish.example.yml
> ci: Rename workflows to improve visibility on github actions

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/core/DefaultNetworkServicesProvider.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/core/DefaultServiceNetworkApi.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/core/di/GiniExampleModule.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationActivity.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationViewModel.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ExtractionsActivity.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/data/Configuration.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/pay/PayViewModel.kt
- bank-sdk/example-app/src/main/res/layout/layout_debug_development_toggles.xml
- bank-sdk/example-app/src/main/res/values/strings.xml
Now in settings page we can change clientId and clientSecret PP-712
> feature(bank-sdk) Add possibility to input client credentials 

- .github/workflows/generate-sboms.yml
> ci: Publish sbom

- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/MainActivity.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/review/ReviewActivity.kt
- health-sdk/example-app/src/main/res/values/strings.xml
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/GiniHealth.kt
> feat(health-sdk): Error message: Multiple documents in a claim

- .github/workflows/internal-payment-sdk.check.yml
- .github/workflows/internal-payment-sdk.release.yml
- .github/workflows/merchant-sdk.check.yml
- RELEASE-ORDER.md
- gini-internal-payment-sdk/LICENSE.md
- gini-internal-payment-sdk/library/build.gradle.kts
- gini-internal-payment-sdk/library/detekt-baseline.xml
- gini-internal-payment-sdk/library/gradle.properties
- merchant-sdk/LICENSE.md
- merchant-sdk/sdk/build.gradle.kts
- settings.gradle.kts
Besides the release workflow I also added a check workflow. I saw the Internal Payment SDK has unit tests.
Important: the workflows will either not trigger or they will fail, because it assumes `gini-internal-payment-sdk/library` will be renamed to `internal-payment-sdk/sdk`. We can ignore failures until the renaming happens.
> Ec 142 setup maven central publishing

- .github/dependabot.yml
> ci: Add depandabot.yml

- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/screens/FileImportErrorDialog.kt
- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/testcases/FileImportErrorDialogTests.kt
Ui Automation for File Import Error Screen
Jira ticket: https://ginis.atlassian.net/browse/PM-30
> Added automation for File Import Error Screen

- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/screens/DigitalInvoiceEditButton.kt
- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/screens/DigitalInvoiceScreen.kt
- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/testcases/DigitalInvoiceEditButtonTests.kt
Added Ui-automation cases for Edit Button on Digital Invoice Screen.
Jira: https://ginis.atlassian.net/browse/PM-27
> Added automation for Edit Button on Digital Invoice Screen.

- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/screens/CaptureScreen.kt
- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/screens/ErrorScreen.kt
- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/testcases/ErrorScreenTests.kt
Ui Automation for Error Screens
Jira ticket: https://ginis.atlassian.net/browse/PM-29
> Added automation for Error Screens

- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/data/model/DocumentWithExtractions.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesActivity.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/model/InvoiceItem.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/review/ReviewActivity.kt
- health-sdk/example-app/src/main/res/layout/item_invoice.xml
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/model/PaymentDetails.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/GiniHealthTest.kt
Made extractions public in PaymentDetails so clients can reach the specific extractions during review and use the data as they want. No new UI element on review component.
> Ipc 331 doctor name extraction

- bank-sdk/example-app/src/main/AndroidManifest.xml
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ExtractionsActivity.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/TransactionDocInvoicePreviewActivity.kt
- bank-sdk/example-app/src/main/res/layout/activity_transaction_doc_invoice_preview.xml
- bank-sdk/example-app/src/main/res/navigation/transaction_doc_invoice_preview_nav_graph.xml
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/di/BankSdkIsolatedKoinContext.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/InvoicePreviewModule.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/InvoicePreviewScreen.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/colors/InvoicePreviewScreenColors.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/colors/section/InvoicePreviewScreenFooterColors.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/usecase/LoadInvoiceBitmapsUseCase.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/transactiondocs/ui/invoice/TransactionDocInvoicePreviewFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/transactiondocs/ui/invoice/TransactionDocInvoicePreviewFragmentState.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/transactiondocs/ui/invoice/TransactionDocInvoicePreviewModule.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/transactiondocs/ui/invoice/TransactionDocInvoicePreviewScreen.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/transactiondocs/ui/invoice/TransactionDocInvoicePreviewViewModel.kt
- bank-sdk/sdk/src/main/res/navigation/gbs_nav_graph.xml
> feature(bank-sdk): Transaction Docs. Added "Delete" button at Invoice Preview

- .github/workflows/gpc.publish.firebase.example.yml
> ci: Add workflow for gini payment controller

- bank-sdk/example-app/src/main/res/values/strings.xml
> fix:(bank-sdk) Change menu item feedback title

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/skonto/DigitalInvoiceSkontoFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/help/SkontoHelpFragment.kt
- bank-sdk/sdk/src/main/res/drawable/gbs_arrow_right.xml
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/button/filled/GiniButton.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/menu/context/GiniDropdownMenu.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/topbar/GiniTopBar.kt
> refactor(bank-sdk): Use drawable resource for back icons

- bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/testcases/CaptureScreenTests.kt
Changes to` test2_flashEnabledWhenImageIsCaptured `function
> Fix failing test cases

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ExtractionsActivity.kt
- bank-sdk/sdk/src/androidTest/java/net/gini/android/bank/sdk/TransferSummaryIntegrationTest.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
> feat:(bank-sdk) Rename releaseCapture with cleanCapture

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/skonto/DigitalInvoiceSkontoFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/InvoicePreviewScreen.kt
- bank-sdk/sdk/src/main/res/values-en/strings.xml
- bank-sdk/sdk/src/main/res/values/strings.xml
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/tooltip/GiniTooltipBox.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/tooltip/GiniTooltipBoxColors.kt
> feature(bank-sdk): Add contentDescription for Skonto

- .github/workflows/bank-sdk.publish.firebase.example.yml
- .github/workflows/health-sdk.publish.firebase.example.yml
- .github/workflows/merchant-sdk.publish.firebase.example.yml
> ci: Change firebase publish actions

- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesActivity.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesViewModel.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/review/ReviewActivity.kt
- health-sdk/example-app/src/main/res/drawable/background_pay_button.xml
- health-sdk/example-app/src/main/res/drawable/background_rounded_corners.xml
- health-sdk/example-app/src/main/res/layout/activity_review.xml
- health-sdk/example-app/src/main/res/layout/button_trust_marker.xml
- health-sdk/example-app/src/main/res/layout/item_invoice.xml
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/GiniHealth.kt
Added `trustMarkersFlow` to `GiniHealth`
Updated example app to show trust markers
> Ipc 375 provide trust markers for entry point 

- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/textinput/amount/DecimalInputVisualTransformation.kt
> feature(bank-sdk): Crash fix

- .github/workflows/bank-api-library.check.yml
- .github/workflows/bank-api-library.docs.build.yml
- .github/workflows/bank-sdk.check.yml
- .github/workflows/bank-sdk.docs.build.yml
- .github/workflows/bank-sdk.publish.example.yml
- .github/workflows/bank-sdk.publish.firebase.example.yml
- .github/workflows/bank-sdk.release.yml
- .github/workflows/capture-sdk.check.yml
- .github/workflows/capture-sdk.docs.build.yml
- .github/workflows/capture-sdk.docs.release.yml
- .github/workflows/core-api-library.check.yml
- .github/workflows/health-api-library.check.yml
- .github/workflows/health-api-library.docs.build.yml
- .github/workflows/health-sdk.check.yml
- .github/workflows/health-sdk.docs.build.yml
- .github/workflows/health-sdk.publish.example.yml
- .github/workflows/health-sdk.publish.firebase.example.yml
- .github/workflows/merchant-sdk.check.yml
- .github/workflows/merchant-sdk.publish.example.yml
- .github/workflows/merchant-sdk.publish.firebase.example.yml
> ci: Concurrency for github actions

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/CaptureFlowActivity.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/CaptureFlowFragment.kt
> feat: (bank-sdk) Add possibility to terminate bank-sdk from outer app

- .github/workflows/bank-api-library.check.yml
- .github/workflows/bank-api-library.docs.build.yml
- .github/workflows/bank-api-library.docs.release.yml
- .github/workflows/bank-api-library.release.yml
- .github/workflows/bank-sdk.check.yml
- .github/workflows/bank-sdk.docs.build.yml
- .github/workflows/bank-sdk.docs.release.yml
- .github/workflows/bank-sdk.publish.firebase.example.yml
- .github/workflows/bank-sdk.release.yml
- .github/workflows/capture-sdk.check.yml
- .github/workflows/capture-sdk.docs.build.yml
- .github/workflows/capture-sdk.docs.release.yml
- .github/workflows/capture-sdk.release.yml
- .github/workflows/core-api-library.check.yml
- .github/workflows/core-api-library.release.yml
- .github/workflows/health-api-library.docs.build.yml
- .github/workflows/health-api-library.docs.release.yml
- .github/workflows/health-api-library.release.yml
- .github/workflows/health-sdk.check.yml
- .github/workflows/health-sdk.docs.build.yml
- .github/workflows/health-sdk.docs.release.yml
- .github/workflows/health-sdk.publish.firebase.example.yml
- .github/workflows/health-sdk.release.yml
- .github/workflows/internal-payment-sdk.check.yml
- .github/workflows/internal-payment-sdk.release.yml
- .github/workflows/merchant-sdk.check.yml
- .github/workflows/merchant-sdk.docs.build.yml
- .github/workflows/merchant-sdk.docs.release.yml
- .github/workflows/merchant-sdk.publish.firebase.example.yml
- .github/workflows/merchant-sdk.release.yml
> Ci: Fix search for the ticket number

- .github/workflows/bank-sdk.publish.firebase.example.yml
- .github/workflows/merchant-sdk.publish.firebase.example.yml
> chore(CI): Added the testing link for firebase app tester 

- health-api-library/library/src/main/java/net/gini/android/health/api/response/ConfigurationResponse.kt
- health-sdk/sdk/src/main/res/values/strings.xml
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/GiniInternalPaymentModule.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/bankselection/BankSelectionBottomSheet.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/moreinformation/MoreInformationFragment.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/paymentComponent/PaymentComponent.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/paymentComponent/PaymentComponentView.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/review/installApp/InstallAppBottomSheet.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/review/openWith/OpenWithBottomSheet.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/review/reviewBottomSheet/ReviewBottomSheet.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/utils/GiniLocalization.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/utils/GiniLocalizationInternal.kt
- internal-payment-sdk/sdk/src/main/res/values-de/strings.xml
- internal-payment-sdk/sdk/src/main/res/values/strings.xml
- internal-payment-sdk/sdk/src/test/java/net/gini/android/internal/payment/GiniInternalPaymentModuleTest.kt
- internal-payment-sdk/sdk/src/test/java/net/gini/android/internal/payment/GiniPaymentPreferencesTest.kt
@danicretu , I have raised this PR to IPC-508 branch related to brand visibility, because this communication tone is also from the same API and you already parsed it. So, we can merge this into IPC-508 after passed review
> IPC-532: SDK communication tone

- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/model/InvoiceItem.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/OrderDetailsFragment.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/model/PaymentDetails.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/util/Extensions.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/model/PaymentDetailsTest.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/review/reviewComponent/ReviewComponent.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/review/reviewComponent/ReviewView.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/utils/CurrencyFormatter.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/utils/Extensions.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/utils/extensions/String.kt
- internal-payment-sdk/sdk/src/test/java/net/gini/android/internal/payment/utils/CurrencyFormatterTest.kt
> fix(internal-payment-sdk): Added `Locale.GERMAN` to amount formatter

- health-sdk/example-app/src/main/res/layout/activity_invoices.xml
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/paymentComponentBottomSheet/PaymentComponentBottomSheet.kt
- internal-payment-sdk/sdk/src/main/res/layout/gps_bottom_sheet_open_with.xml
Fixes already tested and cherry-picked from another branch:
IPC-527
IPC-560
> Ipc 527, Ipc-560

- .github/workflows/bank-sdk.publish.firebase.example.yml
- .github/workflows/health-sdk.publish.firebase.example.yml
- .github/workflows/merchant-sdk.publish.firebase.example.yml
Added the logic to check last three commits if the jira ticket id is not found in last commit
PM-143
> Finding Jira Ticket id in last three commits

- RELEASE-ORDER.md
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesActivity.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/OrderDetailsFragment.kt
- health-sdk/sdk/gradle.properties
- health-sdk/sdk/src/doc/source/setup.rst
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/integratedFlow/PaymentFragment.kt
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
- health-sdk/sdk/src/main/res/layout/ghs_fragment_review.xml
- health-sdk/sdk/src/main/res/layout/ghs_item_page_error.xml
- health-sdk/sdk/src/main/res/values-en/strings.xml
- health-sdk/sdk/src/main/res/values/strings.xml
- internal-payment-sdk/sdk/gradle.properties
Rc branch for health SDK release.
> IPC-594: RC-Health-SDK:5.1.0

- health-api-library/library/src/main/java/net/gini/android/health/api/HealthApiDocumentManager.kt
- health-api-library/library/src/main/java/net/gini/android/health/api/HealthApiDocumentRemoteSource.kt
- health-api-library/library/src/main/java/net/gini/android/health/api/HealthApiDocumentRepository.kt
- health-api-library/library/src/main/java/net/gini/android/health/api/HealthApiDocumentService.kt
- health-api-library/library/src/test/java/net/gini/android/health/api/HealthApiDocumentRemoteSourceTest.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/OrderDetailsViewModel.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/OrdersActivity.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/OrdersAdapter.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/OrdersViewModel.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/data/OrdersLocalDataSource.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/data/OrdersRepository.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/data/model/Order.kt
- health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/orders/data/model/OrderItem.kt
- health-sdk/example-app/src/main/res/layout/item_order.xml
- health-sdk/sdk/src/doc/source/flow.rst
- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/GiniHealth.kt
- health-sdk/sdk/src/test/java/net/gini/android/health/sdk/GiniHealthTest.kt
Deleting a Payment Request
write test for deleting Payment request
> IPC 582 deleting payment request

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/GiniHealth.kt
> fix(health-sdk): fix showing error code

- RELEASE-ORDER.md
- bank-api-library/library/gradle.properties
- bank-sdk/sdk/gradle.properties
- capture-sdk/default-network/gradle.properties
- capture-sdk/sdk/gradle.properties
- core-api-library/library/gradle.properties
> PP-1118:RC-bank-SDK-3.17.0

- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_error.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_noresults.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_error.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_noresults.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_error.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_noresults.xml
> feat(capture-sdk): Change order of buttons in error screens

- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingFragment.java
- capture-sdk/sdk/src/main/res/layout-land/gc_fragment_camera.xml
> Fix(capture-sdk): Fixing the padding on camera screen

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/res/layout-land/gc_fragment_camera.xml
> fix(capture-sdk): fixing the visibility

- capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorFragmentImpl.kt
> fix(capture-sdk): removing the force portrait mode

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationActivity.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationViewModel.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/adapters/CustomErrorNavigationBarBottomAdapter.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/data/Configuration.kt
- bank-sdk/example-app/src/main/res/layout/custom_error_navigation_bar_bottom.xml
- bank-sdk/example-app/src/main/res/layout/layout_bottom_navigation_toggles.xml
- bank-sdk/example-app/src/main/res/values/strings.xml
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/Configuration.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorFragmentImpl.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/error/view/ErrorNavigationBarBottomAdapter.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/noresults/NoResultsFragmentImpl.java
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_error.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_noresults.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_error.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_noresults.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_error.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_noresults.xml
> feat(capture-sdk): Change close to back button in error screens

- bank-api-library/library/src/main/java/net/gini/android/bank/api/models/Configuration.kt
- bank-api-library/library/src/main/java/net/gini/android/bank/api/response/ConfigurationResponse.kt
- capture-sdk/default-network/src/main/java/net/gini/android/capture/network/GiniCaptureDefaultNetworkService.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/network/Configuration.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/provider/GiniBankConfigurationProvider.kt
> feat(bank-sdk): Add configuration flag for qr code education

- capture-sdk/sdk/src/main/res/values-en/strings.xml
- capture-sdk/sdk/src/main/res/values/strings.xml
> feat(capture-sdk): Rename Analysis screen title

- capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/camera/view/QRCodePopup.kt
> feat(capture-sdk): Add talkback for qr code detection message

- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/textinput/GiniTextInput.kt
> feat(bank-sdk): fixing the crash for skonto

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/help/SkontoHelpFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/InvoicePreviewScreen.kt
- capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_help.xml
- capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_help.xml
- capture-sdk/sdk/src/main/res/layout/gc_fragment_help.xml
- capture-sdk/sdk/src/main/res/layout/gc_item_tip.xml
> fix(bank-sdk): enhance accessibility by adding focusable attributes 

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenContent.kt
> fix(bank-sdk): replace key event handling with clickable modifier for date picker

- capture-sdk/sdk/detekt-baseline.xml
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/theme/colors/GiniColorPalette.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/theme/colors/GiniColorPrimirives.kt
- capture-sdk/sdk/src/main/res/values/colors.xml
> feat(capture-sdk): Updating yellow color

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/viewmodel/subintent/OpenExtractionsScreenSubIntent.kt
> bugfix(capture-sdk): Wrong thread result delivery fix

- bank-sdk/sdk/src/main/res/layout/gbs_fragment_digital_invoice_onboarding.xml
> feat(bank-sdk): fixing the scroll issues in RA

- health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
- health-sdk/sdk/src/main/res/layout-land/ghs_fragment_review.xml
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/bankselection/BankSelectionBottomSheet.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/moreinformation/FaqRecyclerAdapter.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/paymentComponentBottomSheet/PaymentComponentBottomSheet.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/review/installApp/InstallAppBottomSheet.kt
- internal-payment-sdk/sdk/src/main/java/net/gini/android/internal/payment/review/openWith/OpenWithBottomSheet.kt
- internal-payment-sdk/sdk/src/main/res/values-de/strings.xml
- internal-payment-sdk/sdk/src/main/res/values-en/strings.xml
- internal-payment-sdk/sdk/src/main/res/values/strings.xml
> feat(health-sdk): fix issues with talk back in health sdk

- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCaptureFragment.kt
> fix(capture-sdk): Fixed the initialization of analytics

- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationActivity.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationViewModel.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/composables/CustomGiniComposableStyleProvider.kt
- bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/data/Configuration.kt
- bank-sdk/example-app/src/main/res/layout/layout_ui_customization_toggles.xml
- bank-sdk/example-app/src/main/res/values/strings.xml
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/Configuration.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenContent.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/InvoicePreviewFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/invoice/InvoicePreviewScreen.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/transactiondocs/ui/invoice/TransactionDocInvoicePreviewFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/transactiondocs/ui/invoice/TransactionDocInvoicePreviewScreen.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingPage.java
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/GiniComposableStyleProvider.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/GiniComposableStyleProviderConfig.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/button/filled/GiniButton.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/button/filled/GiniPrimaryButtonStyleConfig.kt
> feat(capture-sdk): Enable clients to modify the primary button

- capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCaptureFragment.kt
> feat(capture-sdk): crash fix for capture and bank sdk

- capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
- capture-sdk/sdk/src/main/res/values-en/strings.xml
- capture-sdk/sdk/src/main/res/values/strings.xml
> feat(capture-sdk): Adding the landscape title for top bar

- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/theme/modifier/Width.kt
> fix(capture-sdk): Using device type from resources and values

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenContent.kt
> PP-1334: Bringing the view in front while orientation changes

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/skonto/DigitalInvoiceSkontoFragment.kt
- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenContent.kt
> Adjusting Calendar icon and RA+Skonto

- RELEASE-ORDER.md
- RELEASE.md
- bank-api-library/library/gradle.properties
- bank-sdk/sdk/gradle.properties
- capture-sdk/default-network/gradle.properties
- capture-sdk/sdk/gradle.properties
- core-api-library/library/gradle.properties
> RC-Bank-Capture SDK

- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/picker/date/GiniDatePickerDialog.kt
- capture-sdk/sdk/src/main/java/net/gini/android/capture/ui/components/picker/date/GiniDatePickerDialogColors.kt
> feat(bank-sdk): Add container color to date picker in Skonto

- capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisScreenPresenter.java
> PP 1761 blocker:  AnalysisScreenPresenter issues

- bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceScreenPresenter.kt
> PP 1771 DigitalInvoiceScreenPresenter.kt issues
