gini/gini-mobile-android

.github/workflows/health-api-library.check.yml
.github/workflows/health-sdk.check.yml

It's helpful to run all check workflows when we [open and update pull requests](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request). Should help us catch issues early.
The advantage of `pull_request` events is that the workflow is executed on the merged code. In other words the checks are executed on the state we would have after merging the PR.
This article has more info about `pull_request` events: https://frontside.com/blog/2020-05-26-github-actions-pull_request/

ci: Run all checks on pull requests

---

bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/util/CoroutineContinuationHelper.kt

This PR is needed to make Bank SDK's handling payment requests feature work with Xamarin.

feat(bank-sdk): Add helper function for using suspending functions from Java

---

bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/di/ViewModel.kt
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/pay/PayActivity.kt
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/pay/PayViewModelInterface.kt
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/pay/PayViewModelJava.java
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/pay/PayViewModelKotlin.kt

Added a Java implementation of the `PayViewModel` called
`PayViewModelJava` (kotlin version was renamed to
`PayViewModelKotlin`) which shows how to use the suspending
functions from Java.

refactor(bank-sdk): Show how to use suspending functions from Java

---

health-api-library/README.md
health-api-library/library/src/androidTest/assets/payment-provider.json
health-api-library/library/src/androidTest/assets/payment-providers.json
health-api-library/library/src/androidTest/assets/payment-request.json
health-api-library/library/src/androidTest/assets/payment-requests.json
health-api-library/library/src/androidTest/java/net/gini/android/health/api/HealthApiCommunicatorTest.java
health-api-library/library/src/androidTest/java/net/gini/android/health/api/HealthApiDocumentTaskManagerTest.java
health-api-library/library/src/doc/source/guides/common-tasks.rst
health-api-library/library/src/doc/source/guides/getting-started.rst
health-api-library/library/src/doc/source/see_also.rst

I will add the following migration note to the release notes of Health API Library:
It was necessary to reorganise some classes. You only need to replace `core` with `health` for the following classes:
* Replace `net.gini.android.core.api.models.PaymentRequestInput` with `net.gini.android.health.api.models.PaymentRequestInput`.
* Replace `net.gini.android.core.api.models.PaymentProvider`with `net.gini.android.health.api.models.PaymentProvider`.
* Replace `net.gini.android.core.api.DocumentTaskManager`with `net.gini.android.health.api.HealthApiDocumentTaskManager`.
* Replace `net.gini.android.core.api.DocumentManager`
with `net.gini.android.health.api.HealthApiDocumentManager`.
The location of the payment extractions have moved to the compound extractions. Also the label names are now in …

docs(health-api-library): Replace Pay API doc links with links to the Health API docs

---

health-api-library/README.md
health-api-library/library/src/androidTest/assets/payment-provider.json
health-api-library/library/src/androidTest/assets/payment-providers.json
health-api-library/library/src/androidTest/assets/payment-request.json
health-api-library/library/src/androidTest/assets/payment-requests.json
health-api-library/library/src/androidTest/java/net/gini/android/health/api/HealthApiCommunicatorTest.java
health-api-library/library/src/androidTest/java/net/gini/android/health/api/HealthApiDocumentTaskManagerTest.java
health-api-library/library/src/doc/source/guides/common-tasks.rst
health-api-library/library/src/doc/source/guides/getting-started.rst
health-api-library/library/src/doc/source/see_also.rst
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/GiniHealth.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/bank/Bank.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/error/Errors.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/model/PaymentDetails.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/GiniHealthTest.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/requirement/RequirementsTest.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/bank/BankTest.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/model/PaymentDetailsTest.kt

* Changes for working with the Health API.
* Throw `NoPaymentDataExtracted` when the extractions have no `payment` compound extraction.
* Update feedback sending to work with the Health API.

Pia 2177 update health sdk for latest health api library

---

bank-api-library/README.md
bank-api-library/library/src/doc/source/see_also.rst
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/pay/PayActivity.kt
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/pay/PayViewModelInterface.kt
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/pay/PayViewModelJava.java
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/pay/PayViewModelKotlin.kt
bank-sdk/sdk/src/doc/source/capture-features.rst
bank-sdk/sdk/src/doc/source/integration.rst
bank-sdk/sdk/src/doc/source/migrating-from-gvl.rst
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/pay/PaymentRequestIntent.kt
capture-sdk/component-api-example-app/src/main/java/net/gini/android/capture/component/MainActivity.java
capture-sdk/component-api-example-app/src/main/res/layout/activity_main.xml
capture-sdk/default-network/src/main/java/net/gini/android/capture/network/GiniCaptureDefaultNetworkApi.java
capture-sdk/default-network/src/main/java/net/gini/android/capture/network/GiniCaptureDefaultNetworkService.java
capture-sdk/default-network/src/main/java/net/gini/android/capture/network/logging/Util.kt
capture-sdk/default-network/src/main/java/net/gini/android/capture/network/model/ReturnReasonsMapper.java
capture-sdk/example-app-shared-code/src/main/java/net/gini/android/capture/example/shared/BaseExampleApp.java
capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/MainActivity.java
capture-sdk/screen-api-example-app/src/main/res/layout/activity_main.xml
capture-sdk/sdk/src/doc/source/integration.rst
core-api-library/library/src/main/java/net/gini/android/core/api/models/PaymentRequest.kt
core-api-library/library/src/main/java/net/gini/android/core/api/response/PaymentRequestResponse.kt

* Fix Capture SDK and Bank SDK to work with the updated Bank API Library.
* Fix payment request parsing in the Core API Library when `paymentProvider` is not available. 
This happens when using the Pay API in the Bank API Library. The Health API Library was not affected.

Pia 2179 pia 2022 fixes for pay api

---

.github/workflows/capture-sdk.check.yml
bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/ExtractionsActivity.kt
bank-sdk/screen-api-example-app/src/main/res/layout/activity_extractions.xml
bank-sdk/screen-api-example-app/src/main/res/values/strings.xml
bank-sdk/sdk/src/doc/source/integration.rst
capture-sdk/default-network/build.gradle.kts
capture-sdk/default-network/src/main/java/net/gini/android/capture/network/GiniCaptureDefaultNetworkService.java
capture-sdk/default-network/src/test/java/net/gini/android/capture/network/GiniCaptureDefaultNetworkServiceTest.kt
capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/ExtractionsActivity.kt
capture-sdk/screen-api-example-app/src/main/res/layout/activity_extractions.xml
capture-sdk/screen-api-example-app/src/main/res/values/strings.xml
capture-sdk/sdk/src/doc/source/integration.rst

Let clients access the analyzed Gini Bank API document when using the default networking implementation.

Pia 2278 expose document

---

capture-sdk/sdk/src/doc/source/features.rst

docs(capture-sdk): Add the need to add `<queries>` element to manifest when using document import

---

capture-sdk/sdk/src/main/res/values/styles.xml

Bug was caused by Google's Android Material Components library:
https://github.com/material-components/material-components-android/issues/1604
PIA-2487

fix(capture-sdk): Use an alert dialog theme overlay for `gc_accent` to work again with alert dialogs

---

bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/CaptureFlowActivity.kt

Handling the input on activity restarts caused the camera activity to be launched again when the
digital invoice activity returned with a result.
PIA-2785

fix(bank-sdk): Don't handle input in `CaptureFlowActivity` on activity restart

---

bank-sdk/sdk/src/doc/source/customization-guide.rst
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceScreenPresenter.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/LineItemsAdapter.kt
bank-sdk/sdk/src/main/res/values-en/strings.xml
bank-sdk/sdk/src/main/res/values/strings.xml
bank-sdk/sdk/src/test/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceScreenPresenterTest.kt

* Pay button is disabled when total amount is 0 irrelevant of how many items are selected.
* If button is disabled the label is just “Pay”. 
* Added a dedicated string for the disabled pay button title: gbs_digital_invoice_pay_disabled.

Pia 2780 disable pay button if total is zero

---

bank-sdk/sdk/src/doc/source/customization-guide.rst
bank-sdk/sdk/src/main/res/values/colors.xml
bank-sdk/sdk/src/main/res/values/styles.xml

To test it add these lines to `bank-sdk/screen-api-example-app/src/main/res/values/colors.xml`:
```
<color name="gbs_digital_invoice_line_item_details_input_field_cursor">#f00</color>
<color name="gbs_digital_invoice_line_item_details_input_field_selection_highlight">#f0f</color>
```

Pia 2805 input field colors

---

bank-sdk/sdk/src/main/res/layout/gbs_fragment_line_item_details.xml
bank-sdk/sdk/src/main/res/layout/gbs_item_digital_invoice_addon.xml
bank-sdk/sdk/src/main/res/layout/gbs_item_digital_invoice_footer.xml
bank-sdk/sdk/src/main/res/layout/gbs_item_digital_invoice_line_item.xml

To test it please add the following to `bank-sdk/screen-api-example-app/src/main/res/values/themes.xml`. It will make both the integral and fractional parts of prices have the same font size:
```
<style name="GiniCaptureTheme.DigitalInvoice.TotalGrossPrice.Integral.TextStyle" parent="Root.GiniCaptureTheme.DigitalInvoice.TotalGrossPrice.Integral.TextStyle">
<item name="android:textSize">24sp</item>
</style>
<style name="GiniCaptureTheme.DigitalInvoice.TotalGrossPrice.Fractional.TextStyle" parent="Root.GiniCaptureTheme.DigitalInvoice.TotalGrossPrice.Fractional.TextStyle">
<item name="android:textSize">24sp</item>
</style>
<style name="GiniCaptureTheme.DigitalInvoice.LineItem.GrossPrice.Integral.TextStyle" parent="Root.GiniCaptureTheme.DigitalInvoice.LineItem.GrossPrice.Integral.TextStyle"> …
```

Pia 2845 fix text alignment

---

bank-sdk/component-api-example-app/src/main/AndroidManifest.xml
bank-sdk/component-api-example-app/src/main/java/net/gini/android/bank/sdk/componentapiexample/camera/CameraExampleActivity.kt
bank-sdk/screen-api-example-app/src/main/AndroidManifest.xml
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/LineItemsAdapter.kt
capture-sdk/component-api-example-app/src/main/AndroidManifest.xml
capture-sdk/component-api-example-app/src/main/java/net/gini/android/capture/component/camera/CameraExampleAppCompatActivity.java
capture-sdk/screen-api-example-app/src/main/AndroidManifest.xml
capture-sdk/sdk/src/doc/source/features.rst
capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/FileChooserActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/util/ActivityHelper.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/util/AndroidHelper.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/ReviewActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewActivity.java

Note: please review only the commits [ed57c9f](https://github.com/gini/gini-mobile-android/pull/84/commits/ed57c9f1481c136fced8b739eae6cc707734c0d8) and newer.
I replaced all `onBackPressed()` overrides with AndroidX's `OnBackPressedCallbacks`.
The changes have no visible effect. Every back button press or back swipe gesture should work as usual even on Android 13.
The predictive back gesture feature is disabled in Android 13 and can be enabled for testing purposes in the developer tools only. 
It's been a while since android recommends using `OnBackPressedCallbacks` so even though these changes won't have any effect now we are reducing future technical debt.
https://developer.android.com/guide/navigation/predictive-back-gesture
https://android-developers.googleblog.com/2022/07/prepare-you …

Pia 2656 support predictive back gesture

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/noresults/NoResultsFragmentImpl.java

Using the document's intent was not working when multi-page was enabled.
Testing instructions: https://ginis.atlassian.net/browse/PIA-3093?focusedCommentId=19163

fix(capture-sdk): Fix showing/hiding "back to camera" button on No Results Screen

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/storage/ImageDiskStore.java
capture-sdk/sdk/src/test/java/net/gini/android/capture/internal/storage/ImageDiskStoreTest.java

Filenames were generated using `System.currentTimeMillis()` which could return the same value, if called quickly twice.
Switched to using UUIDs for filenames instead.
PIA-3169

fix(capture-sdk): Fix ImageDiskStore generating the same filename twice

---

capture-sdk/screen-api-example-app/src/main/java/net/gini/android/capture/screen/MainActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/camera/view/QRCodePopup.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml

Pia 3234
Custom loading indicator injected in the camera. There was a possible issue with an injected view not working properly, with the progress bar showing only on the first shot, workaround is to inflate the view again in onResume

Pia 3234 camera injected loading indicator

---

bank-api-library/library/build.gradle.kts
core-api-library/library/build.gradle.kts
core-api-library/shared-tests/build.gradle.kts
gradle/libs.versions.toml
health-api-library/library/build.gradle.kts

Fixes security vulnerabilities detected in 3.14.9.
Affects: core-api-library, bank-api-library, health-api-library
PIA-3350

chore: Update okhttp3 to 4.10.0

---

bank-api-library/library/build.gradle.kts
bank-api-library/library/proguard-rules.pro
core-api-library/library/build.gradle.kts
core-api-library/library/proguard-rules.pro
health-api-library/library/build.gradle.kts
health-api-library/library/proguard-rules.pro

Affects: core-api-library, bank-api-library, health-api-library
PIA-3387

fix: Add proguard rule to libraries to preserve all retrofit service interface methods

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisInteractor.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisScreenPresenter.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorType.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/network/NetworkRequestsManager.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/network/FailureException.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/ReviewFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java

While testing with our partially restored backend I found a few issues with our error handling in the analysis screen:
* Errors were lost due to a casting exception from Throwable to FailureException. I made sure that the FailureException is forwarded through the AnalysisInteractor without wrapping it into a RuntimeException. Also I made the casting to fail gracefully and as a fallback show the GENERAL error type.
* The error screen results were not properly handled by the AnalysisActivity. I added the same logic we have in the MultiPageReviewActivity.
* In case of polling timeout we showed NO_CONNECTION error and I replaced it with GENERAL as the general fallback error type.
@llevente Please apply any changes you see fit and merge it afterwards. Thank you!

Pia 3447 fix analysis screen error handling

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisScreenPresenter.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/network/NetworkRequestsManager.java

Don't show the error screen when analysis was cancelled.
PIA-3666

fix(capture-sdk): Fix analysis cancellation handling

---

bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceFragment.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/help/HelpActivity.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/onboarding/DigitalInvoiceOnboardingFragment.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorActivity.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/help/FileImportActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/help/HelpActivity.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/help/PhotoTipsActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/help/SupportedFormatsActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/camera/view/QRCodePopup.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/ui/IntervalClickListener.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/noresults/NoResultsActivity.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/noresults/NoResultsFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingFragment.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingPageFragment.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingScreenContract.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/onboarding/OnboardingScreenPresenter.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/view/ReviewNavigationBarBottomAdapter.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/view/CustomLoadingIndicatorAdapter.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/view/InjectedViewAdapter.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/view/InjectedViewContainer.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/view/NavigationBarTopAdapter.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/view/OnButtonLoadingIndicatorAdapter.kt
capture-sdk/sdk/src/test/java/net/gini/android/capture/onboarding/OnboardingScreenPresenterTest.kt

Fix reuse of `InjectedViewAdapter`s in multiple `InjectedViewContainer`s.
Keep the association between an `InjectedViewAdapter` and an `InjectedViewContainer` in the new
`InjectedViewAdapterInstance` class. This is used to determine when an `InjectedViewContainer`
owns an adapter.
Associate the `InjectedViewAdapter` with the code it needs for configuration by using the new
`InjectedViewAdapterHolder`. This permits the adapter's view to be configured every time the view
is recreated.
The `InjectedViewContainer` that has entered the started state last will take ownership of the `InjectedViewAdapter`, recreate its view, and reconfigure it. When the `InjectedViewContainer` is destroyed it only destroys the `InjectedViewAdapter`'s view if it owns that adapter.

Pia 3799 fix crash when closing camera screen

---

bank-sdk/screen-api-example-app/src/main/res/values/themes.xml
bank-sdk/sdk/src/main/res/values-night/styles.xml
bank-sdk/sdk/src/main/res/values/styles.xml
capture-sdk/sdk/src/main/res/values-night/styles.xml
capture-sdk/sdk/src/main/res/values/styles.xml

By introducing an intermediate "internal" style we can extend the `Root.GiniCaptureTheme` in Bank SDK and when clients override the `GiniCaptureTheme` (which inherits the `Root.GiniCaptureTheme`) they will also inherit the Bank SDK's additions.
Affects: capture-sdk, bank-sdk
PIA-3874

fix: Preserve theme properties from Bank SDK when overriding the `GiniCaptureTheme`

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/MultiPageReviewFragment.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/view/ReviewNavigationBarBottomAdapter.kt
capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml
capture-sdk/sdk/src/main/res/layout/gc_fragment_multi_page_review.xml
capture-sdk/sdk/src/main/res/layout/gc_review_navigation_bar_bottom.xml
capture-sdk/sdk/src/main/res/values-en/strings.xml
capture-sdk/sdk/src/main/res/values/strings.xml

[NOTE]: Contains fix for PIA-3927 also... These were not buttons, but different elements put together in a wrapper layout so the accessibility couldn't work good, because it could select the textview and the image separately and it read the label's text but did not know that it functions as a button.... So everywhere i put a transparent button with the size of the wrapper layout and then the Talkbar reads the text and automatically the "button" part so no string res change needed.... also for the user now the whole "wrapper" (the full button size) is selected (image + text) so it is also more user friendly

WIP: Pia 3928 accessibility talkbar

---

bank-sdk/screen-api-example-app/src/main/java/net/gini/android/bank/sdk/screenapiexample/ExtractionsActivity.kt

[NOTE]: There was no need to reload the list because we're instantly closing the screen so just need to use the updated amount at the cleanup

fix(bank-sdk): Fixed example app feedback UI

---

.github/workflows/bank-sdk.check.yml
.github/workflows/bank-sdk.release.yml
.github/workflows/capture-sdk.check.yml
.github/workflows/capture-sdk.release.yml
.github/workflows/health-sdk.check.yml
.github/workflows/health-sdk.release.yml
bank-sdk/screen-api-example-app/src/debug/AndroidManifest.xml
bank-sdk/screen-api-example-app/src/debug/res/xml/network_security_config.xml
capture-sdk/screen-api-example-app/src/debug/AndroidManifest.xml
capture-sdk/screen-api-example-app/src/debug/res/xml/network_security_config.xml
health-sdk/example-app/build.gradle.kts
health-sdk/example-app/gradle.properties
health-sdk/example-app/src/debug/AndroidManifest.xml
health-sdk/example-app/src/debug/res/xml/network_security_config.xml

* Add the needed network security configuration for [Charles proxy](https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/) to example app debug builds.
* Create release builds in the check workflows. Release builds don't contain the network security configuration and are safe to distribute to clients.

Pia 4104 3.x.x allow charles proxy to intercept https requests

---

.github/workflows/bank-sdk.check.yml
.github/workflows/bank-sdk.release.yml
.github/workflows/capture-sdk.check.yml
.github/workflows/capture-sdk.release.yml
.github/workflows/health-sdk.check.yml
.github/workflows/health-sdk.release.yml
bank-sdk/screen-api-example-app/src/debug/AndroidManifest.xml
bank-sdk/screen-api-example-app/src/debug/res/xml/network_security_config.xml
capture-sdk/screen-api-example-app/src/debug/AndroidManifest.xml
capture-sdk/screen-api-example-app/src/debug/res/xml/network_security_config.xml
health-sdk/example-app/build.gradle.kts
health-sdk/example-app/gradle.properties
health-sdk/example-app/src/debug/AndroidManifest.xml
health-sdk/example-app/src/debug/res/xml/network_security_config.xml

* Add the needed network security configuration for [Charles proxy](https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/) to example app debug builds.
* Create release builds in the check workflows. Release builds don't contain the network security configuration and are safe to distribute to clients.

Pia 4104 2.x.x allow charles proxy to intercept https requests

---

.github/workflows/bank-sdk.check.yml
.github/workflows/bank-sdk.release.yml
.github/workflows/capture-sdk.check.yml
.github/workflows/capture-sdk.release.yml
.github/workflows/health-sdk.check.yml
.github/workflows/health-sdk.release.yml
bank-sdk/screen-api-example-app/src/debug/AndroidManifest.xml
bank-sdk/screen-api-example-app/src/debug/res/xml/network_security_config.xml
capture-sdk/screen-api-example-app/src/debug/AndroidManifest.xml
capture-sdk/screen-api-example-app/src/debug/res/xml/network_security_config.xml
health-sdk/example-app/build.gradle.kts
health-sdk/example-app/gradle.properties
health-sdk/example-app/src/debug/AndroidManifest.xml
health-sdk/example-app/src/debug/res/xml/network_security_config.xml

* Add the needed network security configuration for [Charles proxy](https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/) to example app debug builds.
* Create release builds in the check workflows. Release builds don't contain the network security configuration and are safe to distribute to clients.

Pia 4104 1.x.x allow charles proxy to intercept https requests

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java

It's not critical for our backend that unused documents are deleted.
By removing deletion when leaving the camera screen due to cancellation we eliminate unwanted deletions caused by an unexpected lifecylce behaviour change in Android 13 (onStart is called before onActivityResult in Android 13).

1.x.x - Don't delete image multi-page documents when leaving the camera screen via cancellation

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java

It's not critical for our backend that unused documents are deleted.
By removing deletion when leaving the camera screen due to cancellation we eliminate unwanted deletions caused by an unexpected lifecylce behaviour change in Android 13 (onStart is called before onActivityResult in Android 13).

2.x.x - Don't delete image multi-page documents when leaving the camera screen via cancellation

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraActivity.java

The results of the qr code error screens that were started from the camera screen were ignored. This fix makes sure the results are handled.

PIA-4339 Fix error screen result handling for QR codes in the camera screen

---

core-api-library/library/build.gradle.kts
gradle/libs.versions.toml

Following vulnerability is fixed in okio 3.4.0
https://github.com/advisories/GHSA-w33c-445m-f8w7
PIA-4424

fix(core-api-library): Update okio to 3.4.0 to fix a vulnerability issue

---

.github/workflows/bank-api-library.docs.build.yml
.github/workflows/bank-api-library.docs.release.yml
.github/workflows/bank-sdk.docs.build.yml
.github/workflows/bank-sdk.docs.release.yml
.github/workflows/capture-sdk.docs.build.yml
.github/workflows/capture-sdk.docs.release.yml
.github/workflows/health-api-library.docs.build.yml
.github/workflows/health-api-library.docs.release.yml
.github/workflows/health-sdk.docs.build.yml
.github/workflows/health-sdk.docs.release.yml
bank-api-library/library/build.gradle.kts
bank-api-library/library/src/test/java/net/gini/android/bank/api/BankApiDocumentRemoteSourceTest.kt
core-api-library/library/build.gradle.kts
core-api-library/library/src/main/java/net/gini/android/core/api/DocumentRemoteSource.kt
core-api-library/library/src/main/java/net/gini/android/core/api/authorization/UserRemoteSource.kt
core-api-library/library/src/main/java/net/gini/android/core/api/requests/HttpHeaders.kt
core-api-library/library/src/test/java/net/gini/android/core/api/DocumentRemoteSourceTest.kt
core-api-library/library/src/test/java/net/gini/android/core/api/authorization/UserRemoteSourceTest.kt
core-api-library/library/src/test/java/net/gini/android/core/api/test/DocumentRemoteSourceForTests.kt
core-api-library/library/src/test/java/net/gini/android/core/api/test/MockGiniApiType.kt
health-api-library/library/build.gradle.kts
health-api-library/library/src/test/java/net/gini/android/health/api/HealthApiDocumentRemoteSourceTest.kt

Updates the 2.x.x versions of Bank APi Library, Health API Library and Core API Library.
The change is simple and I used the occasion to improve the bearer and basic related headers code while also adding tests to ensure that capital case "Bearer" and "Basic" is used in authorisation headers.

Pia 4412 2.x.x use capital case "Bearer" instead of all caps "BEARER"

---

bank-api-library/library/build.gradle.kts
bank-api-library/library/src/test/java/net/gini/android/bank/api/BankApiDocumentRemoteSourceTest.kt
core-api-library/library/build.gradle.kts
core-api-library/library/src/main/java/net/gini/android/core/api/DocumentRemoteSource.kt
core-api-library/library/src/main/java/net/gini/android/core/api/authorization/UserRemoteSource.kt
core-api-library/library/src/main/java/net/gini/android/core/api/requests/HttpHeaders.kt
core-api-library/library/src/test/java/net/gini/android/core/api/DocumentRemoteSourceTest.kt
core-api-library/library/src/test/java/net/gini/android/core/api/authorization/UserRemoteSourceTest.kt
core-api-library/library/src/test/java/net/gini/android/core/api/test/DocumentRemoteSourceForTests.kt
core-api-library/library/src/test/java/net/gini/android/core/api/test/MockGiniApiType.kt
health-api-library/library/build.gradle.kts
health-api-library/library/src/test/java/net/gini/android/health/api/HealthApiDocumentRemoteSourceTest.kt

The change is simple and I used the occasion to improve the bearer and basic related headers code while also adding tests to ensure that capital case "Bearer" and "Basic" is used in authorisation headers.

Pia 4412 use capital case "Bearer" instead of all caps "BEARER"

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/qrcode/EPC069_12Parser.java
capture-sdk/sdk/src/test/java/net/gini/android/capture/internal/qrcode/EPC069_12ParserTest.kt

Even though according to the standard only LF (\n) or CRLF (\r\n) line delimiters are allowed some invoice issuers use CR line delimiters.
PIA-4468

fix(capture-sdk): Accept EPC069-12 QR codes with CR (\r) line delimiters

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/qrcode/EPC069_12Parser.java
capture-sdk/sdk/src/test/java/net/gini/android/capture/internal/qrcode/EPC069_12ParserTest.kt

Even though according to the standard only LF (\n) or CRLF (\r\n) line delimiters are allowed some invoice issuers use CR line delimiters.
PIA-4468

fix(capture-sdk): Accept EPC069-12 QR codes with CR (\r) line delimiters in version 1.x.x

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/qrcode/EPC069_12Parser.java
capture-sdk/sdk/src/test/java/net/gini/android/capture/internal/qrcode/EPC069_12ParserTest.kt

Even though according to the standard only LF (\n) or CRLF (\r\n) line delimiters are allowed some invoice issuers use CR line delimiters.
PIA-4468

fix(capture-sdk): Accept EPC069-12 QR codes with CR (\r) line delimiters in version 2.x.x

---

.github/workflows/generate-sboms.yml
bank-api-library/library/build.gradle.kts
bank-sdk/sdk/build.gradle.kts
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/net/gini/gradle/SBOMPlugin.kt
buildSrc/src/main/kotlin/net/gini/gradle/extensions/Project.kt
capture-sdk/default-network/build.gradle.kts
capture-sdk/sdk/build.gradle.kts
core-api-library/library/build.gradle.kts
gradle/libs.versions.toml
health-api-library/library/build.gradle.kts
health-sdk/sdk/build.gradle.kts

Uses the CycloneDX Gradle plugin to generate SBOMs for every projects.

Ipc 68 generate SBOM

---

bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationActivity.kt
bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/ConfigurationViewModel.kt
bank-sdk/example-app/src/main/java/net/gini/android/bank/sdk/exampleapp/ui/data/Configuration.kt
bank-sdk/example-app/src/main/res/layout/activity_configuration.xml
bank-sdk/example-app/src/main/res/values/strings.xml
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/CaptureFlowFragment.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/Configuration.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceBottomSheet.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/DigitalInvoiceFragment.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/digitalinvoice/ReturnReasonsDialog.kt
bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/util/WindowExtensions.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCapture.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/GiniCaptureFragment.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/FileChooserFragment.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/ui/AlertDialogFragment.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/util/AlertDialogHelperCompat.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/util/WindowExtensions.kt

- Adds a new configuration option to Capture SDK and Bank SDK to allow or disallow screenshots. By default screenshots are allowed.
- Also adds this new configuration option to the example app's configuration screen.
The new configuration option can be used as follows:
* Capture SDK: 
```
GiniCapture.newInstance(context)
.setAllowScreenshots(false) // or true
...
.build()
```
* Bank SDK: 
```
GiniBank.setCaptureConfiguration(context, CaptureConfiguration(
allowScreenshots = false, // or true
...
))
```
Note: builds upon the host fragments branch which we plan to be our upcoming version. In the extreme case that our release of that is delayed we can easily port this to work with latest version we have in `main`.

Pp 226 prevent screenshots

---

health-sdk/sdk/src/doc/source/customization.rst
health-sdk/sdk/src/main/res/layout/ghs_fragment_payment_more_information.xml
health-sdk/sdk/src/main/res/layout/ghs_item_faq_answer.xml
health-sdk/sdk/src/main/res/values-night/colors.xml
health-sdk/sdk/src/main/res/values/colors.xml

- Adds customization guide for the Payment Feature Info Screen.
- Adds dark mode color for the FAQ list divider.
You can download the rendered integration guide from the Checks tab -> Build docs for Health SDK -> Click on the "health-sdk-documentation" artifact. This will download the `health-sdk-documentation.zip`. 
Extract the zip, and open `html/index.html` to view the integration guide.

Ipc 215 more information screen UI customization guide

---

health-sdk/sdk/src/main/java/net/gini/android/health/sdk/paymentcomponent/PaymentComponent.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/installApp/InstallAppBottomSheet.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/installApp/InstallAppViewModel.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/paymentComponent/PaymentComponentTest.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewFragmentTest.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewViewModelTest.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/installApp/InstallAppBottomSheetTest.kt

Refactors the data flow of the selected payment provider app by modifying:
- the PaymentComponent to update the selected app when rechecking the installed state
- the review fragment and the "install app bottom sheet" to use PaymentComponent's `selectedPaymentProviderAppFlow` as the source of truth for the payment provider app
This way the data flow is reactive: "recheck installed state" event is sent to PaymentComponent which then emits an updated selected payment provider app downstream to the review fragment and the "install app bottom sheet". These then update their UI and state accordingly.

Ipc 240 data flow refactor

---

health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/data/InvoicesLocalDataSource.kt
health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/data/InvoicesRepository.kt
health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/data/model/DocumentWithExtractions.kt
health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesActivity.kt
health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/ui/InvoicesViewModel.kt

IPC-261 Previously extracted information visible on `InvoicesActivity`

---

health-sdk/sdk/src/main/java/net/gini/android/health/sdk/GiniHealth.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt

IPC-279
I opted not to change `StateFlow` to `SharedFlow` as I found that adding an imperceptible delay when emitting 2 consecutive events fixed the issue. It's a smaller change in my opinion, with less impact on the codebase. I'm open to discussions if switching to `SharedFlow` is the preferred route.
Please note: when tapping on `Retry`, the snackbar flickers when being dismissed. It **might** be related to [this](https://github.com/material-components/material-components-android/issues/648) bug that has apparently been fixed. I say **might** because we're not using `animateLayoutChanges` anywhere. 
It's happening on `main` branch as well, and in all cases when the snackbar is shown - I haven't figured out a solution...

feat(health-sdk): Fixed error not showing in 'share with' scenario

---

.github/workflows/bank-api-library.release.yml
.github/workflows/bank-sdk.release.yml
.github/workflows/capture-sdk.release.yml
.github/workflows/core-api-library.release.yml
.github/workflows/health-api-library.release.yml
.github/workflows/health-sdk.release.yml

Since beginning of June 2024 a user token is required for publishing to Maven Central: https://central.sonatype.org/publish/generate-token/
I have already added the user token to the GitHub Action [secrets](https://github.com/gini/gini-mobile-android/settings/secrets/actions).
This is an email from Sonatype informing me about the user token:

ci: Log-in to Maven Central with user token

---

health-sdk/example-app/src/main/java/net/gini/android/health/sdk/exampleapp/invoices/data/InvoicesRepository.kt

I applied a learning from a coroutines talk to use `map { async {} }` to make test invoice uploads and refreshes faster.

refactor(health-sdk): Use `async` in example app to parallelize test invoice uploads and refresh requests

---

health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewFragment.kt
health-sdk/sdk/src/main/java/net/gini/android/health/sdk/review/ReviewViewModel.kt
health-sdk/sdk/src/test/java/net/gini/android/health/sdk/review/ReviewFragmentTest.kt

Fix iban validation appearing AFTER the bottom sheets are displayed - first validate IBAN, then continue with the flow.

Fix(health sdk) fixes for ipc 304

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/help/FileImportHelpFragment.kt

We need to check if fragment visible, if not we don't need to show snackBar, it cause a crash
PM-91

fix(capture-sdk): Fix Handler delayed call

---

capture-sdk/sdk/src/main/AndroidManifest.xml
capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/FileChooserFragment.kt
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/providerchooser/ProvidersAdapter.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/providerchooser/ProvidersAppItemSelectedListener.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/providerchooser/ProvidersAppWrapperItem.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/fileimport/providerchooser/ProvidersItem.java
capture-sdk/sdk/src/main/res/drawable/gc_photo_picker_app_icon.xml

Now we are using new photo picker, for devices that doesn't have backdrop version, we use the same approach with list of apps PM-198

feat(capture-sdk): Use new photo-picker.

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/ui/FragmentImplCallback.java

If we close fragment before photo recognition finished, it cause a crash. This happens because we try to navigate from wrong location. That's why I have added safeNavigation function PP-496

fix(capture-sdk): Fix a crash with navigation.

---

bank-sdk/example-app/src/main/res/values/styles.xml
capture-sdk/sdk/src/main/res/values/styles.xml
health-sdk/example-app/src/main/res/values/styles.xml
health-sdk/sdk/src/main/res/values/styles.xml

fix(mobile-android) Change navigationBar color

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/camera/CameraFragmentImpl.java
capture-sdk/sdk/src/main/res/drawable-sw600dp/gc_camera_frame.xml
capture-sdk/sdk/src/main/res/drawable/gc_camera_frame.xml
capture-sdk/sdk/src/main/res/drawable/gc_detection_error_background.xml
capture-sdk/sdk/src/main/res/layout-sw600dp-land/gc_fragment_camera.xml
capture-sdk/sdk/src/main/res/layout-sw600dp/gc_fragment_camera.xml
capture-sdk/sdk/src/main/res/layout/gc_detection_error_layout.xml
capture-sdk/sdk/src/main/res/layout/gc_fragment_camera.xml
capture-sdk/sdk/src/main/res/values-en/strings.xml
capture-sdk/sdk/src/main/res/values-sw600dp/dimens.xml
capture-sdk/sdk/src/main/res/values/dimens.xml
capture-sdk/sdk/src/main/res/values/strings.xml

feat(capture-sdk) Add inform "qr code not available" message

---

.github/workflows/health-api-library.check.yml
core-api-library/shared-tests/src/main/java/net/gini/android/core/api/test/shared/GiniCoreAPIIntegrationTest.kt
health-api-library/library/src/androidTest/java/net/gini/android/health/api/GiniHealthAPIIntegrationTest.kt

Allows running the Health API integration tests also on staging (`health-api.stage.gini.net` and `user.stage.gini.net`).
There are a few differences when running tests on staging:
- certificate pinning is disabled because staging hosts use self-signed SSL certificates and pinning fails due to the lack of a trust anchor (`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`)
- running tests on Android 23 or older is disabled for the same reason as above
- `testGetPayment()` is disabled because it needs access to the staging Pay API (pay-api.pia.stage.gini.net) which requires VPN access (via Tailscale).
Workflow can be manually triggered from [here](https://github.com/gini/gini-mobile-android/actions/workflows/health-api-library.check.yml) by using …

Run health api library check manually on stage

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/qrcode/PaymentQRCodeReader.java

Ignore CancellationExcpetion because our qrcode detection task was just canceled, we don't need to trigger onQRCodeReaderFail event PP-814

fix: (capture-sdk) Ignore CancellationException

---

capture-sdk/sdk/src/main/java/net/gini/android/capture/internal/qrcode/PaymentQRCodeReader.java

@mahdiabolfazli 
Somewhere we trying to close image after detection twice, this cause IllegalStateException
I propose to check this exception, but after release research and found problem why we try to close image twice.

Ec 46 iban fix

---

capture-sdk/sdk/src/main/res/values-en/strings.xml
capture-sdk/sdk/src/main/res/values/strings.xml

Left only name of the button, without "button" word, because talkback pronounce button twice PP-220

fix(capture-sdk): Remove button in description

---

bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/testcases/DigitalInvoiceEditButtonTests.kt
bank-sdk/example-app/src/androidTest/java/net/gini/android/bank/sdk/exampleapp/ui/testcases/ErrorScreenTests.kt

Fix failing for the assertions of following test-cases:
- DigitalInvoiceEditButtonTests > test9_verifyInlineErrorWhenNameFieldIsEmpty 
- ErrorScreenTests > test2_verifyNetworkErrorScreen

Fix failing test cases

---

.github/workflows/bank-api-library.check.yml
.github/workflows/bank-api-library.docs.build.yml
.github/workflows/bank-sdk.check.yml
.github/workflows/bank-sdk.docs.build.yml
.github/workflows/bank-sdk.publish.example.yml
.github/workflows/bank-sdk.publish.firebase.example.yml
.github/workflows/capture-sdk.check.yml
.github/workflows/capture-sdk.docs.build.yml
.github/workflows/core-api-library.check.yml
.github/workflows/health-api-library.check.yml
.github/workflows/health-api-library.docs.build.yml
.github/workflows/health-sdk.check.yml
.github/workflows/health-sdk.docs.build.yml
.github/workflows/health-sdk.publish.example.yml
.github/workflows/health-sdk.publish.firebase.example.yml
.github/workflows/merchant-sdk.check.yml
.github/workflows/merchant-sdk.publish.example.yml
.github/workflows/merchant-sdk.publish.firebase.example.yml

ci: Remove push trigger for build actions. Upgrade pull_request trigger

---

bank-api-library/library/src/main/java/net/gini/android/bank/api/BankApiDocumentRepository.kt
bank-api-library/library/src/main/java/net/gini/android/bank/api/TrackingAnalysisRemoteSource.kt
bank-api-library/library/src/main/java/net/gini/android/bank/api/TrackingAnalysisService.kt
bank-api-library/library/src/main/java/net/gini/android/bank/api/requests/AmplitudeBody.kt
core-api-library/library/src/main/java/net/gini/android/core/api/internal/GiniCoreAPIBuilder.kt

feature(bank-sdk): Amplitude. Changed API url to Gini proxy

---

internal-payment-sdk/sdk/src/main/res/layout-land/gps_fragment_payment_more_information.xml

feat(internal-sdk): Added FAQ landscape UI
